export enum TIMELINE_EVENTS_TYPES {
  NEW_CHALLENGE = "NEW_CHALLENGE",
  CHALLENGE_ACCEPTED = "CHALLENGE_ACCEPTED",
  BUY_CREDITS = "BUY_CREDITS",
  WITHDRAW_MONEY = "WITHDRAW_MONEY",
  CHALLENGE_CANCELED = "CHALLENGE_CANCELED",
}
